### ISSUE TITLE
have fractal generator only return a result between 0 and 1

### ISSUE THREAD

**Issue by Fiskie** [Fiskie/Autocity#1]

**Comment by WhiplashD** [comment]
Well I could only get it to clamp sub-zero values. Trying to math.min the integers is  throwing an NPE so i dunno

**Comment by WhiplashD** [comment]
Ok I tried working on this for about 3 hours and I couldn't do it. At the end I was even explicitly testing for true/false cases of negative numbers and explicitly assigning them to 0 and they were still outputting as negative.

**Comment by WhiplashD** [comment]
Alright, values seem to be consistently clamped between 0.00 and 1.00. HOWEVER there are outliers when using an extreme roughness value (like 1.0 for instance) which will still cause negatives. We can look into that some more later
